### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: AuthenticView - AI for body positivity
email: kevinmloeffler@gmail.com
description: AuthenticView is a free AI-driven browser extension which identifies where images have been manipulated to promote an unrealistic body image.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://authenticview.beauty" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#9dd3eb'
twitter_username: Loefflerlabs
github_username:  kevinl95
author: Kevin Loeffler and Sara Reitz
logo: assets/images/large-logo.png
twitter:
  username: Loefflerlabs
social:
  name: Kevin Loeffler and Sara Reitz
  links:
    - https://twitter.com/loefflerlabs
    - https://kevinloeffler.com
    - https://github.com/kevinl95

languages: ["en"]
ampdir: amp

github: https://github.com/kevinl95/AuthenticView

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
