name: AuthenticView
description: AuthenticView is a free AI-driven browser extension which identifies where images have been manipulated to promote an unrealistic body image.
full_description: 'AuthenticView lets you right click images on the web and have an AI highlight where it detects the image has been touched up with photoshop, especially with smoothing tools and filters.<br>
<br>- Always free
<br>- Available for Google Chrome'
#android: https://telegra.ph/Replace-this-link-07-23
#iOS: https://telegra.ph/Replace-this-link-07-23
web: https://github.com/kevinl95/AuthenticView
screenshots:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  - 4.jpg
#producthunt: https://telegra.ph/Replace-this-link-07-23
#companies:
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: androidpolice.png
#  - url: https://telegra.ph/Replace-this-link-07-23
#    image: producthunt.png
